################################################################################
#
#   Fungal gene expression in dust from the International Space Station (ISS)
#                      
#       Balasubrahmaniam et al 2024. Exposure to elevated relative humidity
#        in laboratory chambers alters fungal gene expression in dust from 
#                the International Space Station (ISS).
#
#                       By: Neeraja Balasubrahmaniam
#
################################################################################

# Script name: ISS_PCA_adonis2
# Created on: 25 January 2024
# Last updated: 05 May 2024
# Author: Neeraja Balasubrahmaniam
# Description: This script plots the PCA of gene expression of all genes grouped
# by ERH and by Bag (Fig.1a and 1b).  
# Inkscape [v.1.3] (https://inkscape.org/) was used to finalize figures.
# This script also performs statistical testing to determine significant differences
# of the gene expression data when grouped by ERH condition using adonis2. 

# ---- Setup for PCA -----------------------------------------------------------
# Install necessary packages
install.packages("tidyverse")
install.packages("vegan")
install.packages("glue")
install.packages("ape")
install.packages("patchwork")
install.packages("ggplot2")

# Load packages
library(tidyverse)
library(vegan)
library(glue)
library(ape)
library(patchwork)
library(ggplot2)

# Package versions
packageVersion("tidyverse")
packageVersion("vegan")
packageVersion("glue")
packageVersion("ape")
packageVersion("patchwork")
packageVersion("ggplot2")

# Reporting packages versions 
# > packageVersion("tidyverse")
# [1] ‘2.0.0’
# > packageVersion("vegan")
# [1] ‘2.6.4’
# > packageVersion("glue")
# [1] ‘1.6.2’
# > packageVersion("ape")
# [1] ‘5.7.1’
# > packageVersion("patchwork")
# [1] ‘1.1.2’
# > packageVersion("ggplot2")
# [1] ‘3.4.3’

# ---- Setup for Statistical testing -------------------------------------------
# Install necessary packages
install.packages(vegan)
install.packages('devtools')
library(devtools)
install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
install.packages("tidyverse")
install.packages("readxl")

# Load packages
library(vegan)
library(pairwiseAdonis)
library(tidyverse)
library(readxl)

# Package versions
packageVersion("vegan")
packageVersion("pairwiseAdonis")
packageVersion("tidyverse")
packageVersion("readxl")

# Reporting packages versions 
# > packageVersion("vegan")
# [1] ‘2.6.4’
# > packageVersion("pairwiseAdonis")
# [1] ‘0.4.1’
# > packageVersion("tidyverse")
# [1] ‘2.0.0’
# > packageVersion("readxl")
# [1] ‘1.4.3’

# ======================= PCA ==============================================================================
# Set working directory to read data
setwd("") # path of directory in ""

# Principal Component (PC) Scores on the log2 and row mean centered Counts per Million (CPM)
# matrix were generated by Trinity. The file is called:
# "RSEM.gene.counts.matrix.minRow10.CPM.log2.centered.PCA.prcomp.scores".
# The underlying gene expression counts file (RSEM.gene.counts.matrix) on which PCA 
# was performed to obtain PC scores is also provided in the GitHub folder.

# Load PC data
data=read.table(file="RSEM.gene.counts.matrix.minRow10.CPM.log2.centered.PCA.prcomp.scores", 
                header = TRUE, sep='	');
df1 <- data.frame(data)
df1 = df1[,c(1,2)] # We plot only PC1 and PC2
df1 <- cbind(Samples = rownames(df1), df1)

# Read a samples to ERH file to use for grouping
Samples_RH=read.table(file="sample_text_file_HUMID_ALL.txt", header = FALSE, sep='	');
colnames(Samples_RH) <- c("ERH", "Samples", "Bag")

# merge PC1, PC2 and Samples to RH file
df_PCA = merge(Samples_RH, df1, by = "Samples")

# Factor by ERH 
df_PCA$ERH <- factor(df_PCA$ERH, levels = c("100%", "85%", "50%"))

# Plotting PCA of gene expression grouped by ERH condition
p1 = ggplot(df_PCA, aes(x = PC1, y = PC2, color = ERH, shape = ERH)) +
  geom_point(size=5) +
  scale_shape_manual(values=c(15, 17, 19)) +
  scale_fill_manual(values=c('darkblue','#98be72', '#fdbb2d'))+
  scale_color_manual(values=c('darkblue','#98be72', '#fdbb2d'))+
  stat_ellipse(geom = "polygon",
               aes(fill = ERH), 
               alpha = 0.3, size = 0.5) +  
  xlab("PC1 (32.11%)") + 
  ylab("PC2 (10.97%)") +
  xlim(-0.42,0.32) +    #changing plot X axis limits if needed
  ylim(-0.9,0.9) +    #changing plot Y axis limits if needed
  theme(axis.text.y   = element_text(size=16),
        axis.text.x   = element_text(size=16),
        axis.title.y  = element_text(size=16),
        axis.title.x  = element_text(size=16),
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5)
  ) 

# Save p1 PCA as PDF if needed
#pdf(file = "PC1vsPC2_Rplot_HUMID_ALL2.pdf", height = 5, width = 7)
#p1
#dev.off()

# Plotting PCA of gene expression grouped by Bag
p2 = ggplot(df_PCA, aes(x = PC1, y = PC2, color = `Bag`, shape = `ERH`)) +
  geom_point(size=5) +
  scale_shape_manual(values=c(15, 17, 19)) +
  scale_color_manual(values=c('#fc8d62ff','#a6d854ff', '#ffd92fff','#c77cffff'))+
  xlab("PC1 (32.11%)") + 
  ylab("PC2 (10.97%)") +
  xlim(-0.42,0.32) +    #changing plot X axis limits if needed
  ylim(-0.9,0.9) +    #changing plot Y axis limits if needed
  theme(axis.text.y   = element_text(size=16),
        axis.text.x   = element_text(size=16),
        axis.title.y  = element_text(size=16),
        axis.title.x  = element_text(size=16),
        legend.text = element_text(size=16),
        legend.title = element_text(size=16),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=0.5)
  ) 
p2

# Save p2 as PDF if needed
#pdf(file = "PC1vsPC2_Rplot_HUMID_Bag.pdf", height = 4, width = 11)
#p2
#dev.off()

# Combine plots and save as PDF
pdf(file = "PC1vsPC2_Rplot_HUMID_ERH_Bag.pdf", height = 4, width = 11)
p1 + p2
dev.off()

# =================Statistical Analysis using adonis2=======================================================

#---- Test if ERH groups are significantly different based on gene expression data --------------

#---- Set working directory to read gene expression raw counts data
setwd("")

# ---- Load gene expression data for PCA
data_gene = readRDS("RSEM.gene.counts.matrix.rds") # load gene counts matrix
data_gene = data_gene[rowSums(data_gene)>=10,] # remove genes which when summed across samples < 10
cs = colSums(data_gene) 
data_gene = t( t(data_gene)/cs) * 1e6; # Counts per Million (CPM)
data_gene = log2(data_gene+1) # log transformation of CPM values
data_gene = t(data_gene)

#---- Get Euclidean distances---------------------------------------------------
euclid <- vegdist(data_gene, method = "euclidean")    # Euclidean distance

#---- Get a samples-to-RH file in the same sample order as the primary_data
meta_gene=read.table(file="sample_text_file_HUMID_ALL.txt", header = FALSE, 
                     sep='	'); 
colnames(meta_gene)=c("RH", "Sample", "Bag")
meta_gene$Sample <- paste("X", meta_gene$Sample, sep="")

euclid <- vegdist(data_gene, method = "euclidean")      # Euclidean distance
euclid = euclid/1000    # scaling values between 0 and 1: does not change downstream analysis
euclid.matrix = as.matrix(euclid)               # Euclidean distance as matrix
euclid.df = as.data.frame(euclid.matrix)
euclid.df <- cbind(rownames(euclid.df), data.frame(euclid.df, row.names=NULL))
colnames(euclid.df)[1]="Sample"


#---- Create a combined matrix with RH and distance data------------------------
euclid.df.meta = inner_join(meta_gene, euclid.df, by="Sample")

#Are groups different based on RH: Permanova testing using adonis2
PERMANOVA_gene <- adonis2(euclid ~ RH, data = euclid.df.meta, 
                          permutations = 10000)
p_gene = PERMANOVA_gene$`Pr(>F)`[1]
R2_gene = PERMANOVA_gene$R2[1]
print(p_gene)
print(R2_gene)

#---- Perform pairwise adonis as post-hoc---------------------------------------
# for gene expression; using FDR adjustment to control for multiple comparisons
pairwise.p_all.dist = pairwise.adonis2(euclid~RH, data = euclid.df.meta, 
                                       nperm=10000)

pairwise_p_final = numeric()

pairwise_p_final["RH_50vs85_p"] = pairwise.p_all.dist[["50%_vs_85%"]][["Pr(>F)"]][1]
pairwise_p_final["RH_50vs100_p"] = pairwise.p_all.dist[["50%_vs_100%"]][["Pr(>F)"]][1]
pairwise_p_final["RH_85vs100_p"] = pairwise.p_all.dist[["85%_vs_100%"]][["Pr(>F)"]][1]

pairwise_p_adjust_final = p.adjust(pairwise_p_final, method = "BH")
pairwise_p_adjust_final = as.data.frame(pairwise_p_adjust_final)

print(pairwise_p_adjust_final)


